In [3]:
from skllm import MultiLabelZeroShotGPTClassifier
import pandas as pd

In [4]:
# Load the Reddit life tips dataset
data = pd.read_csv('data/helpfulRedditPosts.csv')

In [5]:
data.head()

,id,author,isOver18,postUrl,subreddit,postTitle,hasPostBody,postBody,score,numComments,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,f6jt5e,w2555,False,https://reddit.com/r/LifeProTips/comments/f6jt5e/,LifeProTips,"LPT: keep your mouth shut, and don't volunteer...",True,I had a phone interview scheduled this morning...,147296.0,4730.0,NaN,NaN,NaN,NaN,NaN
1,lq1jn7,this1tyme,False,https://reddit.com/r/LifeProTips/comments/lq1jn7/,LifeProTips,"LPT: Texans, you are about to experience the w...",False,NaN,134320.0,4121.0,NaN,NaN,NaN,NaN,NaN
2,j2mm1b,raviji22,False,https://reddit.com/r/LifeProTips/comments/j2mm1b/,LifeProTips,"LPT: When you sign up for anything online, put...",False,NaN,129513.0,1971.0,NaN,NaN,NaN,NaN,NaN
3,fqkkke,[deleted],False,https://reddit.com/r/LifeProTips/comments/fqkkke/,LifeProTips,"LPT: First rule of family gatherings, always b...",True,[deleted],124219.0,2762.0,NaN,NaN,NaN,NaN,NaN
4,gmmiah,AlphaSyncz,False,https://reddit.com/r/YouShouldKnow/comments/gm...,YouShouldKnow,"YSK That there is a Youtuber called ""Dad, how ...",True,It's just basic stuff but I know friends of mi...,120038.0,1532.0,NaN,NaN,NaN,NaN,NaN

In [6]:
data.describe()

               score  numComments  Unnamed: 13  Unnamed: 14
count       9.000000     9.000000      4.00000     2.000000
mean   125228.444444  2604.222222    937.75000    80.000000
std     10248.934592  1217.272954    771.05831    55.154329
min    115511.000000   964.000000    272.00000    41.000000
25%    118582.000000  1792.000000    314.00000    60.500000
50%    120038.000000  2633.000000    812.50000    80.000000
75%    129513.000000  2933.000000   1436.25000    99.500000
max    147296.000000  4730.000000   1854.00000   119.000000

In [7]:
X = data['postBody']

In [ ]:
# Define candidate labels
candidate_labels = [
    "High Importance",
    "Medium Importance",
    "Low Importance",
]

# Create and fit the classifier
clf = MultiLabelZeroShotGPTClassifier(max_labels=1)  # Set max_labels to 1 as each tip has a single level of importance
clf.fit(None, [candidate_labels])

In [ ]:
# Predict the labels
labels = clf.predict(X)

In [ ]:
# Add labels to the dataset and save
data['Importance'] = labels
data.to_csv('classified_tips.csv', index=False)